# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoteTestResolutionClient.ui'
#
# Created: Thu Nov 02 09:38:50 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_Client(object):
    def setupUi(self, MainWindow_Client):
        MainWindow_Client.setObjectName(_fromUtf8("MainWindow_Client"))
        MainWindow_Client.resize(1080, 800)
        MainWindow_Client.setMinimumSize(QtCore.QSize(1080, 800))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8(u"宋体"))
        font.setPointSize(10)
        MainWindow_Client.setFont(font)
        MainWindow_Client.setAcceptDrops(False)
        self.centralwidget = QtGui.QWidget(MainWindow_Client)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_connect = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_connect.setGeometry(QtCore.QRect(10, 0, 1061, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8(u"宋体"))
        self.groupBox_connect.setFont(font)
        self.groupBox_connect.setObjectName(_fromUtf8("groupBox_connect"))
        self.label_ServerIP = QtGui.QLabel(self.groupBox_connect)
        self.label_ServerIP.setGeometry(QtCore.QRect(20, 20, 70, 29))
        self.label_ServerIP.setObjectName(_fromUtf8("label_ServerIP"))
        self.lineEdit_Port = QtGui.QLineEdit(self.groupBox_connect)
        self.lineEdit_Port.setGeometry(QtCore.QRect(360, 20, 61, 23))
        self.lineEdit_Port.setObjectName(_fromUtf8("lineEdit_Port"))
        self.label_Port = QtGui.QLabel(self.groupBox_connect)
        self.label_Port.setGeometry(QtCore.QRect(320, 20, 31, 29))
        self.label_Port.setObjectName(_fromUtf8("label_Port"))
        self.pushButton_Connect = QtGui.QPushButton(self.groupBox_connect)
        self.pushButton_Connect.setGeometry(QtCore.QRect(620, 20, 75, 25))
        self.pushButton_Connect.setObjectName(_fromUtf8("pushButton_Connect"))
        self.lineEdit_ServerIP = QtGui.QLineEdit(self.groupBox_connect)
        self.lineEdit_ServerIP.setGeometry(QtCore.QRect(90, 20, 201, 23))
        self.lineEdit_ServerIP.setObjectName(_fromUtf8("lineEdit_ServerIP"))
        self.label_Port_2 = QtGui.QLabel(self.groupBox_connect)
        self.label_Port_2.setGeometry(QtCore.QRect(470, 20, 61, 29))
        self.label_Port_2.setObjectName(_fromUtf8("label_Port_2"))
        self.lineEdit_Timeout = QtGui.QLineEdit(self.groupBox_connect)
        self.lineEdit_Timeout.setGeometry(QtCore.QRect(530, 20, 61, 23))
        self.lineEdit_Timeout.setObjectName(_fromUtf8("lineEdit_Timeout"))
        self.groupBox_vesa = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_vesa.setGeometry(QtCore.QRect(10, 50, 1061, 411))
        self.groupBox_vesa.setObjectName(_fromUtf8("groupBox_vesa"))
        self.pushButton_load_data = QtGui.QPushButton(self.groupBox_vesa)
        self.pushButton_load_data.setGeometry(QtCore.QRect(10, 20, 131, 23))
        self.pushButton_load_data.setObjectName(_fromUtf8("pushButton_load_data"))
        self.pushButton_export_data = QtGui.QPushButton(self.groupBox_vesa)
        self.pushButton_export_data.setGeometry(QtCore.QRect(160, 20, 131, 23))
        self.pushButton_export_data.setObjectName(_fromUtf8("pushButton_export_data"))
        self.tableWidget_vesa = QtGui.QTableWidget(self.groupBox_vesa)
        self.tableWidget_vesa.setEnabled(True)
        self.tableWidget_vesa.setGeometry(QtCore.QRect(10, 50, 1041, 351))
        self.tableWidget_vesa.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget_vesa.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_vesa.setAutoScrollMargin(16)
        self.tableWidget_vesa.setDragEnabled(False)
        self.tableWidget_vesa.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidget_vesa.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_vesa.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_vesa.setObjectName(_fromUtf8("tableWidget_vesa"))
        self.tableWidget_vesa.setColumnCount(21)
        self.tableWidget_vesa.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(0, 20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_vesa.setItem(1, 20, item)
        self.tableWidget_vesa.horizontalHeader().setVisible(True)
        self.tableWidget_vesa.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_vesa.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget_vesa.horizontalHeader().setHighlightSections(True)
        self.tableWidget_vesa.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_vesa.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_vesa.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_vesa.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_vesa.verticalHeader().setStretchLastSection(False)
        self.pushButton_send_data = QtGui.QPushButton(self.groupBox_vesa)
        self.pushButton_send_data.setGeometry(QtCore.QRect(310, 20, 75, 23))
        self.pushButton_send_data.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.pushButton_send_data.setObjectName(_fromUtf8("pushButton_send_data"))
        self.pushButton_NvAPI_Status = QtGui.QPushButton(self.groupBox_vesa)
        self.pushButton_NvAPI_Status.setGeometry(QtCore.QRect(400, 20, 75, 23))
        self.pushButton_NvAPI_Status.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pushButton_NvAPI_Status.setObjectName(_fromUtf8("pushButton_NvAPI_Status"))
        self.groupBox_log = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_log.setGeometry(QtCore.QRect(10, 460, 1051, 291))
        self.groupBox_log.setObjectName(_fromUtf8("groupBox_log"))
        self.textEdit_log = QtGui.QTextEdit(self.groupBox_log)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 20, 941, 261))
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName(_fromUtf8("textEdit_log"))
        self.pushButton_clear = QtGui.QPushButton(self.groupBox_log)
        self.pushButton_clear.setGeometry(QtCore.QRect(960, 20, 75, 23))
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.pushButton_save = QtGui.QPushButton(self.groupBox_log)
        self.pushButton_save.setGeometry(QtCore.QRect(960, 50, 75, 23))
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        MainWindow_Client.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_Client)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        MainWindow_Client.setMenuBar(self.menubar)
        self.action_save = QtGui.QAction(MainWindow_Client)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_exit = QtGui.QAction(MainWindow_Client)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_help = QtGui.QAction(MainWindow_Client)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about = QtGui.QAction(MainWindow_Client)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_open = QtGui.QAction(MainWindow_Client)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.menu_file.addAction(self.action_open)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow_Client)
        QtCore.QObject.connect(self.pushButton_clear, QtCore.SIGNAL(_fromUtf8("released()")), self.textEdit_log.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Client)
        MainWindow_Client.setTabOrder(self.lineEdit_ServerIP, self.lineEdit_Port)
        MainWindow_Client.setTabOrder(self.lineEdit_Port, self.lineEdit_Timeout)
        MainWindow_Client.setTabOrder(self.lineEdit_Timeout, self.pushButton_Connect)
        MainWindow_Client.setTabOrder(self.pushButton_Connect, self.pushButton_load_data)
        MainWindow_Client.setTabOrder(self.pushButton_load_data, self.pushButton_export_data)
        MainWindow_Client.setTabOrder(self.pushButton_export_data, self.pushButton_send_data)
        MainWindow_Client.setTabOrder(self.pushButton_send_data, self.tableWidget_vesa)
        MainWindow_Client.setTabOrder(self.tableWidget_vesa, self.textEdit_log)
        MainWindow_Client.setTabOrder(self.textEdit_log, self.pushButton_clear)
        MainWindow_Client.setTabOrder(self.pushButton_clear, self.pushButton_save)

    def retranslateUi(self, MainWindow_Client):
        MainWindow_Client.setWindowTitle(_translate("MainWindow_Client", "RemoteTestResolutionClient", None))
        self.groupBox_connect.setTitle(_translate("MainWindow_Client", "连接PC", None))
        self.label_ServerIP.setText(_translate("MainWindow_Client", "ServerIP:", None))
        self.label_Port.setText(_translate("MainWindow_Client", "Port:", None))
        self.pushButton_Connect.setText(_translate("MainWindow_Client", "Connect", None))
        self.label_Port_2.setText(_translate("MainWindow_Client", "Timeout:", None))
        self.groupBox_vesa.setTitle(_translate("MainWindow_Client", "分辨率远程操作", None))
        self.pushButton_load_data.setText(_translate("MainWindow_Client", "载入分辨率参数", None))
        self.pushButton_export_data.setText(_translate("MainWindow_Client", "导出分辨率参数", None))
        self.tableWidget_vesa.setSortingEnabled(False)
        item = self.tableWidget_vesa.verticalHeaderItem(0)
        item.setText(_translate("MainWindow_Client", "1", None))
        item = self.tableWidget_vesa.verticalHeaderItem(1)
        item.setText(_translate("MainWindow_Client", "2", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_Client", "显示器ID", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_Client", "显示器名称", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_Client", "计时标准(N)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_Client", "宽", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow_Client", "高", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow_Client", "颜色深度(C)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow_Client", "帧率(Hz)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow_Client", "H活动像素(A)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow_Client", "V活动像素(A)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow_Client", "H前沿(像素)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow_Client", "V前沿(像素)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow_Client", "H同步宽度(像素)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow_Client", "V同步宽度(像素)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow_Client", "H总像素(X)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow_Client", "V总像素(X)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow_Client", "H极性(Y)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow_Client", "V极性(Y)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow_Client", "刷新率(Hz)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow_Client", "V刷新率(KHz)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow_Client", "像素时钟(MHz)", None))
        item = self.tableWidget_vesa.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow_Client", "时序名称", None))
        __sortingEnabled = self.tableWidget_vesa.isSortingEnabled()
        self.tableWidget_vesa.setSortingEnabled(False)
        item = self.tableWidget_vesa.item(0, 0)
        item.setText(_translate("MainWindow_Client", "001", None))
        item = self.tableWidget_vesa.item(0, 1)
        item.setText(_translate("MainWindow_Client", "ViewSonic VA2206H-LED", None))
        item = self.tableWidget_vesa.item(0, 2)
        item.setText(_translate("MainWindow_Client", "手动", None))
        item = self.tableWidget_vesa.item(0, 3)
        item.setText(_translate("MainWindow_Client", "1080", None))
        item = self.tableWidget_vesa.item(0, 4)
        item.setText(_translate("MainWindow_Client", "720", None))
        item = self.tableWidget_vesa.item(0, 5)
        item.setText(_translate("MainWindow_Client", "32", None))
        item = self.tableWidget_vesa.item(0, 6)
        item.setText(_translate("MainWindow_Client", "50", None))
        item = self.tableWidget_vesa.item(0, 7)
        item.setText(_translate("MainWindow_Client", "1080", None))
        item = self.tableWidget_vesa.item(0, 8)
        item.setText(_translate("MainWindow_Client", "720", None))
        item = self.tableWidget_vesa.item(0, 9)
        item.setText(_translate("MainWindow_Client", "88", None))
        item = self.tableWidget_vesa.item(0, 10)
        item.setText(_translate("MainWindow_Client", "4", None))
        item = self.tableWidget_vesa.item(0, 11)
        item.setText(_translate("MainWindow_Client", "44", None))
        item = self.tableWidget_vesa.item(0, 12)
        item.setText(_translate("MainWindow_Client", "8", None))
        item = self.tableWidget_vesa.item(0, 13)
        item.setText(_translate("MainWindow_Client", "2200", None))
        item = self.tableWidget_vesa.item(0, 14)
        item.setText(_translate("MainWindow_Client", "1125", None))
        item = self.tableWidget_vesa.item(0, 15)
        item.setText(_translate("MainWindow_Client", "正", None))
        item = self.tableWidget_vesa.item(0, 16)
        item.setText(_translate("MainWindow_Client", "正", None))
        item = self.tableWidget_vesa.item(0, 17)
        item.setText(_translate("MainWindow_Client", "67", None))
        item = self.tableWidget_vesa.item(0, 18)
        item.setText(_translate("MainWindow_Client", "60", None))
        item = self.tableWidget_vesa.item(0, 19)
        item.setText(_translate("MainWindow_Client", "148.5", None))
        item = self.tableWidget_vesa.item(0, 20)
        item.setText(_translate("MainWindow_Client", "CUST:1024x768x60Hz", None))
        item = self.tableWidget_vesa.item(1, 0)
        item.setText(_translate("MainWindow_Client", "002", None))
        item = self.tableWidget_vesa.item(1, 1)
        item.setText(_translate("MainWindow_Client", "Philips 227E4LH", None))
        item = self.tableWidget_vesa.item(1, 2)
        item.setText(_translate("MainWindow_Client", "手动", None))
        item = self.tableWidget_vesa.item(1, 3)
        item.setText(_translate("MainWindow_Client", "1600", None))
        item = self.tableWidget_vesa.item(1, 4)
        item.setText(_translate("MainWindow_Client", "1200", None))
        item = self.tableWidget_vesa.item(1, 5)
        item.setText(_translate("MainWindow_Client", "16", None))
        item = self.tableWidget_vesa.item(1, 6)
        item.setText(_translate("MainWindow_Client", "60", None))
        item = self.tableWidget_vesa.item(1, 7)
        item.setText(_translate("MainWindow_Client", "1600", None))
        item = self.tableWidget_vesa.item(1, 8)
        item.setText(_translate("MainWindow_Client", "1200", None))
        item = self.tableWidget_vesa.item(1, 9)
        item.setText(_translate("MainWindow_Client", "88", None))
        item = self.tableWidget_vesa.item(1, 10)
        item.setText(_translate("MainWindow_Client", "4", None))
        item = self.tableWidget_vesa.item(1, 11)
        item.setText(_translate("MainWindow_Client", "44", None))
        item = self.tableWidget_vesa.item(1, 12)
        item.setText(_translate("MainWindow_Client", "8", None))
        item = self.tableWidget_vesa.item(1, 13)
        item.setText(_translate("MainWindow_Client", "2200", None))
        item = self.tableWidget_vesa.item(1, 14)
        item.setText(_translate("MainWindow_Client", "1125", None))
        item = self.tableWidget_vesa.item(1, 15)
        item.setText(_translate("MainWindow_Client", "负", None))
        item = self.tableWidget_vesa.item(1, 16)
        item.setText(_translate("MainWindow_Client", "负", None))
        item = self.tableWidget_vesa.item(1, 17)
        item.setText(_translate("MainWindow_Client", "67", None))
        item = self.tableWidget_vesa.item(1, 18)
        item.setText(_translate("MainWindow_Client", "60", None))
        item = self.tableWidget_vesa.item(1, 19)
        item.setText(_translate("MainWindow_Client", "148.5", None))
        item = self.tableWidget_vesa.item(1, 20)
        item.setText(_translate("MainWindow_Client", "CUST:1024x768x60Hz", None))
        self.tableWidget_vesa.setSortingEnabled(__sortingEnabled)
        self.pushButton_send_data.setText(_translate("MainWindow_Client", "发送数据", None))
        self.pushButton_NvAPI_Status.setText(_translate("MainWindow_Client", "错误码查询", None))
        self.groupBox_log.setTitle(_translate("MainWindow_Client", "日志", None))
        self.textEdit_log.setHtml(_translate("MainWindow_Client", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>", None))
        self.pushButton_clear.setText(_translate("MainWindow_Client", "清除", None))
        self.pushButton_save.setText(_translate("MainWindow_Client", "保存", None))
        self.menu_file.setTitle(_translate("MainWindow_Client", "文件", None))
        self.menu_help.setTitle(_translate("MainWindow_Client", "帮助", None))
        self.action_save.setText(_translate("MainWindow_Client", "保存日志", None))
        self.action_exit.setText(_translate("MainWindow_Client", "退出", None))
        self.action_help.setText(_translate("MainWindow_Client", "使用说明", None))
        self.action_about.setText(_translate("MainWindow_Client", "关于", None))
        self.action_open.setText(_translate("MainWindow_Client", "打开文件", None))
